# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "82684b9c90b060ea281898363de52219"
name = "kartai"
handle = "kartai"
application_url = "https://dayton-handy-ml-administration.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cart-transform-api.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dayton-handy-ml-administration.trycloudflare.com/auth/callback",
  "https://dayton-handy-ml-administration.trycloudflare.com/auth/shopify/callback",
  "https://dayton-handy-ml-administration.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
